
export const TRANSLATIONS = {
  ta: {
    appName: 'வார்ப்பர்',
    dashboard: 'முகப்பு',
    stock: 'சரக்கு (Stock)',
    accounts: 'கணக்கு (Accounts)',
    profile: 'சுயவிவரம்',
    totalBalance: 'மொத்த இருப்பு',
    income: 'வரவு',
    expense: 'செலவு',
    addStock: 'சரக்கு சேர்',
    addTransaction: 'கணக்கு சேர்',
    editTransaction: 'கணக்கை மாற்ற',
    itemName: 'பொருளின் பெயர்',
    quantity: 'அளவு',
    price: 'விலை',
    category: 'வகை',
    save: 'சேமி',
    update: 'புதுப்பிக்க',
    cancel: 'ரத்து',
    photo: 'புகைப்படம்',
    noData: 'தகவல் ஏதும் இல்லை',
    lowStock: 'குறைவான இருப்பு',
    syncNotice: 'ஒரே கணக்கில் லாகின் செய்தால் அனைத்து மொபைல்களிலும் பார்க்கலாம்.',
    clearAll: 'அனைத்தையும் அழிக்க',
    confirmDeleteTxn: 'இந்த கணக்கை நீக்கவா?',
    confirmClearTxn: 'அனைத்து கணக்குகளையும் அழிக்கவா?',
    cantUndo: 'இதை மாற்ற முடியாது.',
    mobile: 'மொபைல் எண்',
    otp: 'OTP குறியீடு',
    sendOtp: 'OTP அனுப்பு',
    verify: 'சரிபார்',
    accountNotFound: 'இந்த கணக்கு இன்னும் உருவாக்கப்படவில்லை.',
    createAsk: 'புதியதாக கணக்கு தொடங்கவா?',
    yes: 'ஆம், தொடங்கு',
    no: 'வேண்டாம்',
    otpSent: 'OTP அனுப்பப்பட்டது: ',
    invalidOtp: 'தவறான OTP',
    loginFailed: 'தவறான தகவல்கள்',
    emailOrMobile: 'இமெயில் / மொபைல் எண்',
    selectCategoryFirst: 'முதலில் வகையை தேர்ந்தெடுக்கவும்',
    color: 'நிறம்',
    sleeve: 'கை வகை',
    fullHand: 'முழுக்கை',
    halfHand: 'அரைக்கை',
    size: 'சைஸ்',
    skipLogin: 'உள்நுழையாமல் தொடரவும்',
    selectColor: 'நிறத்தை தேர்ந்தெடுக்கவும்',
    partyName: 'பெயர் (Customer/Dealer)',
    ledger: 'பேரேடு (Ledger)',
    transactions: 'பரிவர்த்தனைகள்',
    receivable: 'நமக்கு வரவேண்டியது',
    payable: 'நாம் தரவேண்டியது',
    netBalance: 'மொத்த கணக்கு',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    resetPassword: 'கடவுச்சொல் மீட்டெடுப்பு',
    sendResetLink: 'லிங்க் அனுப்புக',
    backToLogin: 'திரும்ப செல்ல',
    resetLinkSent: 'கடவுச்சொல் மீட்டெடுப்பு லிங்க் மின்னஞ்சலுக்கு அனுப்பப்பட்டது.',
    // Warpers
    warpers: 'வார்ப்பர்கள்',
    addWarper: 'கடை சேர்',
    name: 'பெயர்',
    phone: 'மொபைல் எண்',
    searchWarpers: 'வார்ப்பர்களைத் தேடு',
    totalDispatched: 'மொத்த நூல் செலவு',
    totalReturned: 'மொத்த வார்ப்பு வரவு',
    balanceAtWarper: 'வார்ப்பரிடம் உள்ள இருப்பு',
    dispatched: 'நூல் செலவு',
    returned: 'வார்ப்பு வரவு',
    orders: 'ஆர்டர்கள்',
    allWarps: 'அனைத்து வார்ப்புகள்',
    addDispatch: 'நூல் செலவு சேர்',
    addReturn: 'வார்ப்பு வரவு சேர்',
    createWarpOrder: 'வார்ப்பு ஆர்டர் உருவாக்கு',
    bobbinOrder: 'பாபின் ஆர்டர்',
    topWarpOrder: 'மேல் வார்ப்பு ஆர்டர்',
    createBobbinOrder: 'பாபின் ஆர்டர் உருவாக்கு',
    createTopWarpOrder: 'மேல் வார்ப்பு ஆர்டர் உருவாக்கு',
    manageFormulas: 'சூத்திரங்களை நிர்வகி',
    date: 'தேதி',
    weightKg: 'எடை (kg)',
    billNumber: 'பில் எண்',
    supplier: 'சப்ளையர்',
    weaver: 'நெசவாளர்',
    ends: 'இலைகள்',
    designName: 'டிசைன் பெயர்',
    warpYarn: 'வார்ப்பு நூல்',
    weftYarn: 'ஊடை நூல்',
    totalSarees: 'மொத்த சேலைகள்',
    warpLength: 'வார்ப்பு நீளம்',
    totalWeight: 'மொத்த எடை',
    gramsPer1End: '1 இலைக்கு எத்தனை கிராம்?',
    formulaFor: 'சூத்திரம்',
    grams: 'கிராம்',
    deleteFormula: 'சூத்திரத்தை நீக்கு',
    addNewFormula: 'புதிய சூத்திரம் சேர்',
    denier: 'டெனியர்',
    gramsPerEnd: 'ஒரு இலைக்கு கிராம்',
    assignToWeaver: 'நெசவாளருக்கு ஒதுக்கு',
    loomNumber: 'தறி எண்',
    wagePerSaree: 'ஒரு சேலைக்கு கூலி',
    wagePaid: 'கூலி வழங்கப்பட்டது',
    searchWeaver: 'நெசவாளரைத் தேடு',
    selectLoom: 'தறியைத் தேர்ந்தெடு',
    newLoom: 'புதிய தறி',
    breakType: 'பிரேக் வகை',
    rightBreak: 'வலது பிரேக்',
    leftBreak: 'இடது பிரேக்',
    assign: 'ஒதுக்கு',
    statement: 'அறிக்கை',
    fromDate: 'தொடக்க தேதி',
    toDate: 'முடிவு தேதி',
    viewStatement: 'அறிக்கையைப் பார்',
    successAddWarper: 'கடை வெற்றிகரமாக சேர்க்கப்பட்டது!',
    confirmDelete: 'நிச்சயமாக நீக்க வேண்டுமா?',
    weightOrEndsRequired: 'எடை அல்லது இலை அளவு தேவை',
    successAddReturn: 'வார்ப்பு வரவு வெற்றிகரமாக சேமிக்கப்பட்டது!',
    successAddDispatch: 'நூல் செலவு வெற்றிகரமாக சேமிக்கப்பட்டது!',
    fillAllDetails: 'அனைத்து விவரங்களையும் நிரப்பவும்',
    fillEndsColorsCorrectly: 'அனைத்து இலைகளும் மற்றும் கலர்களும் சரியாக உள்ளிடவும்',
    section: 'பகுதி',
    stockLabel: 'ஸ்டாக் (Stock)',
    // Profile
    editProfile: 'சுயவிவரத்தை திருத்து',
    settings: 'அமைப்புகள்',
    language: 'மொழி',
    changeLanguage: 'பயன்பாட்டின் மொழியை மாற்றவும்',
    colorSettings: 'நிற அமைப்புகள்',
    changeColors: 'பின்னணி மற்றும் பட்டன் நிறங்களை மாற்றவும்',
    backgroundColor: 'பின்னணி நிறம்',
    buttonColor: 'பட்டன் நிறம்',
    appNameLabel: 'பயன்பாட்டின் பெயர்',
    setShopName: 'உங்கள் கடையின் பெயரை அமைக்கவும்',
    shopNamePlaceholder: 'எ.கா: முருகன் டெக்ஸ்டைல்ஸ்',
    server: 'சர்வர்',
    connected: 'இணைக்கப்பட்டது',
    offline: 'ஆஃப்லைன்',
    dbConnection: 'தரவுத்தள இணைப்பு',
    configOnlineStorage: 'ஆன்லைன் சேமிப்பகத்தை அமைக்கவும்',
    setup: 'அமை',
    logout: 'வெளியேறவும்',
    loginSignUp: 'லாகின் / பதிவு',
    address: 'முகவரி',
    saveChanges: 'சேமி',
    changeColorAsk: 'நிறத்தை மாற்றவா?',
    applyColorConfirm: 'நீங்கள் தேர்ந்தெடுத்த நிறத்திற்கு மாற்ற விரும்புகிறீர்களா?',
    apply: 'மாற்று',
    setupCloudDatabase: 'கிளவுட் டேட்டாபேஸ் செட்டிங்ஸ்',
    saveAndConnect: 'சேமி',
    saving: 'சேமிக்கப்படுகிறது...',
    dbNotConfiguredAlert: 'டேட்டாபேஸ் இணைக்கப்படவில்லை! தயவுசெய்து .env ஃபைலில் Supabase URL மற்றும் Key-ஐ சேர்த்து ஆப்பை மீண்டும் பில்ட் செய்யவும். அல்லது Guest Mode-ல் சென்று Profile -> Setup Server மூலம் இணைக்கவும்.',
    regSuccessPhoneNote: 'பதிவு வெற்றி! (குறிப்பு: மொபைல் லாகின் வேலை செய்ய Supabase-ல் Phone Provider-ஐ ஆன் செய்யவும்)',
    regSuccessLoginNow: 'பதிவு வெற்றி! இப்போது லாகின் செய்யவும்.',
    invalidCredentials: 'தவறான இமெயில்/மொபைல் அல்லது கடவுச்சொல்',
    loginRequired: 'உள்நுழைய',
    pleaseLoginToContinue: 'தொடர உங்கள் கணக்கில் நுழையவும்',
    loginLabel: 'லாகின்',
    signUpLabel: 'புதிய கணக்கு',
    kg: 'கிலோ',
    g: 'கிராம்',
    loading: 'ஏற்றப்படுகிறது...',
    installAppTitle: 'அப்ளிகேஷனை நிறுவுங்கள்',
    installAppDesc: 'வேகமான அணுகலுக்கு உங்கள் போனில் நிறுவுங்கள்',
    installNow: 'இப்போதே நிறுவு',
  },
  en: {
    appName: 'Warper',
    dashboard: 'Dashboard',
    stock: 'Stock',
    accounts: 'Accounts',
    profile: 'Profile',
    totalBalance: 'Total Balance',
    income: 'Income',
    expense: 'Expense',
    addStock: 'Add Stock',
    addTransaction: 'Add Entry',
    editTransaction: 'Edit Entry',
    itemName: 'Item Name',
    quantity: 'Quantity',
    price: 'Price',
    category: 'Category',
    save: 'Save',
    update: 'Update',
    cancel: 'Cancel',
    photo: 'Photo',
    noData: 'No Data',
    lowStock: 'Low Stock',
    syncNotice: 'Login to sync data across devices.',
    clearAll: 'Clear All',
    confirmDeleteTxn: 'Delete this entry?',
    confirmClearTxn: 'Clear all entries?',
    cantUndo: 'This cannot be undone.',
    mobile: 'Mobile Number',
    otp: 'OTP Code',
    sendOtp: 'Send OTP',
    verify: 'Verify',
    accountNotFound: 'Account not created yet.',
    createAsk: 'Do you want to create a new account?',
    yes: 'Yes, Create',
    no: 'No',
    otpSent: 'OTP Sent: ',
    invalidOtp: 'Invalid OTP',
    loginFailed: 'Invalid credentials',
    emailOrMobile: 'Email / Mobile Number',
    selectCategoryFirst: 'Select Category First',
    color: 'Color',
    sleeve: 'Sleeve',
    fullHand: 'Full Hand',
    halfHand: 'Half Hand',
    size: 'Size',
    skipLogin: 'Skip Login (Guest Mode)',
    selectColor: 'Select Color',
    partyName: 'Party Name (Customer/Dealer)',
    ledger: 'Ledger',
    transactions: 'Transactions',
    receivable: 'Receivable',
    payable: 'Payable',
    netBalance: 'Net Balance',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetLinkSent: 'Password reset link sent to your email.',
    // Warpers
    warpers: 'Warpers',
    addWarper: 'Add Shop',
    name: 'Name',
    phone: 'Phone',
    searchWarpers: 'Search Warpers',
    totalDispatched: 'Total Dispatched',
    totalReturned: 'Total Returned',
    balanceAtWarper: 'Balance at Warper',
    dispatched: 'Dispatched',
    returned: 'Returned',
    orders: 'Orders',
    allWarps: 'All Warps',
    addDispatch: 'Add Dispatch',
    addReturn: 'Add Return',
    createWarpOrder: 'Create Warp Order',
    bobbinOrder: 'Bobbin Order',
    topWarpOrder: 'Top Warp Order',
    createBobbinOrder: 'Create Bobbin Order',
    createTopWarpOrder: 'Create Top Warp Order',
    manageFormulas: 'Manage Formulas',
    date: 'Date',
    weightKg: 'Weight (kg)',
    billNumber: 'Bill Number',
    supplier: 'Supplier',
    weaver: 'Weaver',
    ends: 'Ends',
    designName: 'Design Name',
    warpYarn: 'Warp Yarn',
    weftYarn: 'Weft Yarn',
    totalSarees: 'Total Sarees',
    warpLength: 'Warp Length',
    totalWeight: 'Total Weight',
    gramsPer1End: 'Grams per 1 End?',
    formulaFor: 'Formula for',
    grams: 'grams',
    deleteFormula: 'Delete Formula',
    addNewFormula: 'Add New Formula',
    denier: 'Denier',
    gramsPerEnd: 'Grams per End',
    assignToWeaver: 'Assign to Weaver',
    loomNumber: 'Loom Number',
    wagePerSaree: 'Wage per Saree',
    wagePaid: 'Wage Paid',
    searchWeaver: 'Search Weaver',
    selectLoom: 'Select Loom',
    newLoom: 'New Loom',
    breakType: 'Break Type',
    rightBreak: 'Right Break',
    leftBreak: 'Left Break',
    assign: 'Assign',
    statement: 'Statement',
    fromDate: 'From Date',
    toDate: 'To Date',
    viewStatement: 'View Statement',
    successAddWarper: 'Shop added successfully!',
    confirmDelete: 'Are you sure you want to delete?',
    weightOrEndsRequired: 'Weight or Ends required',
    successAddReturn: 'Warp return saved successfully!',
    successAddDispatch: 'Yarn dispatch saved successfully!',
    fillAllDetails: 'Please fill all details',
    fillEndsColorsCorrectly: 'Please fill all ends and colors correctly',
    section: 'Section',
    stockLabel: 'Stock',
    // Profile
    editProfile: 'Edit Profile',
    settings: 'Settings',
    language: 'Language',
    changeLanguage: 'Change app language',
    colorSettings: 'Color Settings',
    changeColors: 'Change background and button colors',
    backgroundColor: 'Background Color',
    buttonColor: 'Button Color',
    appNameLabel: 'App Name',
    setShopName: 'Set your shop name',
    shopNamePlaceholder: 'e.g., Murugan Textiles',
    server: 'Server',
    connected: 'Connected',
    offline: 'Offline',
    dbConnection: 'Database Connection',
    configOnlineStorage: 'Configure online storage',
    setup: 'Setup',
    logout: 'Logout',
    loginSignUp: 'Login / Sign Up',
    address: 'Address',
    saveChanges: 'Save Changes',
    changeColorAsk: 'Change Color?',
    applyColorConfirm: 'Are you sure you want to apply the selected color?',
    apply: 'Apply',
    setupCloudDatabase: 'Setup Cloud Database',
    saveAndConnect: 'Save & Connect',
    saving: 'Saving...',
    dbNotConfiguredAlert: 'Database not configured! Please add Supabase URL and Key in .env file and rebuild the app. Or go to Guest Mode -> Profile -> Setup Server to configure.',
    regSuccessPhoneNote: 'Success! (Note: Enable Phone Provider in Supabase for mobile login)',
    regSuccessLoginNow: 'Success! Please login.',
    invalidCredentials: 'Invalid email/mobile or password',
    loginRequired: 'Login Required',
    pleaseLoginToContinue: 'Please login to continue',
    loginLabel: 'Login',
    signUpLabel: 'Sign Up',
    kg: 'kg',
    g: 'g',
    loading: 'Loading...',
    installAppTitle: 'Install Application',
    installAppDesc: 'Install on your phone for faster access',
    installNow: 'Install Now',
  }
};

export const CATEGORIES = [
  'Shirts (சட்டைகள்)',
  'Pants (பேன்ட்)',
  'Accessories (பாகங்கள்)',
  'ஆண்கள் ஆடை (Men)',
  'பெண்கள் ஆடை (Women)',
  'டாப்ஸ் (Tops)',
  'கணவன் மனைவி காம்போ (Couple Combo)',
  'ஃபேமிலி காம்போ (Family Combo)'
];

export const SHIRT_SIZES = [
  'S-36',
  'M-38',
  'L-40',
  'XL-42',
  'XXL-44'
];

export const PREDEFINED_COLORS = [
  { name: 'கருப்பு', code: '#000000', text: 'white' }, // Black
  { name: 'வெள்ளை', code: '#FFFFFF', text: 'black' }, // White
  { name: 'கிரே', code: '#6B7280', text: 'white' }, // Grey
  { name: 'நேவி ப்ளூ', code: '#1E3A8A', text: 'white' }, // Navy Blue
  { name: 'ஸ்கை ப்ளூ', code: '#0EA5E9', text: 'black' }, // Sky Blue
  { name: 'ரெட்', code: '#DC2626', text: 'white' }, // Red
  { name: 'தக்காளி', code: '#EF4444', text: 'white' }, // Tomato
  { name: 'ஆரஞ்சு', code: '#F97316', text: 'white' }, // Orange
  { name: 'மஞ்சள்', code: '#FACC15', text: 'black' }, // Yellow
  { name: 'மஸ்டர்ட்', code: '#CA8A04', text: 'white' }, // Mustard
  { name: 'சந்தனம்', code: '#FDE68A', text: 'black' }, // Sandal
  { name: 'B. கிரீன்', code: '#064E3B', text: 'white' }, // Bottle Green
  { name: 'சட்னி', code: '#16A34A', text: 'white' }, // Chutney
  { name: 'L. கிரீன்', code: '#86EFAC', text: 'black' }, // L.Green
  { name: 'மெரூன்', code: '#800000', text: 'white' }, // Maroon
  { name: 'பிங்க்', code: '#EC4899', text: 'white' }, // Pink
  { name: 'L.பிங்க்', code: '#F9A8D4', text: 'black' }, // L.Pink
  { name: 'ஊதா', code: '#7C3AED', text: 'white' }, // Purple
  { name: 'எல் வைலட்', code: '#A78BFA', text: 'black' }, // L.Violet
  { name: 'லாவெண்டர்', code: '#C4B5FD', text: 'black' }, // Lavender
  { name: 'ரெக்ஸோனா', code: '#2DD4BF', text: 'black' }, // Rexona
  { name: 'காபி', code: '#78350F', text: 'white' } // Coffee
];

export const YARN_TYPES = [
  '50d', '80d', '75d', '68d', '34d', '30kota', 'multi kota', '110d', '150d', 'Half Fine Zari', 'Tested Zari', 'Imitation Zari', '30 டோப் கோட்டா', '30 டய்டு கோட்டா', '34D&68D', '30kota dope', '30d dyed kota', 'Copper zari', 'Silver zari', 'Gold zari', 'Pink copper zari', 'ஜரிகை'
];

export const YARN_COLORS = [
  'red', 'black', 'rani', 'b.green', 'green', 'rexona', 'sumathi', 'tusser', 'cream', 'babha', 'gold', 'pink', 'violet', 'வெள்ளை', 'காப்பர்', 'ஆர் ப்ளூ', 'மெரூன்', 'நாகப்பழம்', 'லெமன்', 'சில்வர்', 'பிங்க் காப்பர்'
];
